/* This is the test file for myFilter function
 *    PLEASE DO NOT EDIT THIS FILE
 * To run these tests do `mocha spec/myFilterSpec.js`
*/

var mocha = require('mocha');
var chai = require('chai');
var spies = require('chai-spies');
chai.use(spies);

var expect = chai.expect;
chai.config.includeStack = false; // turn off stack trace
chai.config.showDiff = true; // turn on reporter diff display

var myFilter = require('../myFilter');

var testCallBack;

describe('myFilter', function(){
	// Sample Data
	beforeEach(function() {
	  testArr = [0, 1, 100, 1000];
	  function testCallback(element){
	  	return (element > 50);
	  }
	});

	it('should do the same thing as prototype.array.filter()', function(){
		let answer = testArr.filter(testCallback);
		let mySolution = myFilter(testArr, testCallback);

		for (i in answer){
			if (answer[i] !== mySolution[i]){
				return false;
			}
		}
		return true;
	});

});
